<?php

namespace app\backend\controllers;

use app\common\models\Category;
use app\common\services\Constants;
use yii\data\Pagination;

/**
 * Class CategoryController
 * @package app\backend\controllers
 * 分类
 */
class CateController extends BaseController
{
    public function afterAction($action, $result)
    {
        $admin_name = \Yii::$app->session['admin_name'];
        $admin_id = \Yii::$app->session['admin_id'];
//        $this->layout = true;
        if (empty($admin_name) || empty($admin_id)) {
            $this->redirect('/user/login');
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


    const PAGE = 1;
    const PAGE_SIZE = 10;

    private static function pagination($pageNo, $count)
    {
        $pagination = new Pagination([
            'defaultPageSize' => self::PAGE_SIZE,
            'totalCount' => $count,
        ]);
        $pagination->setPage($pageNo);
        return $pagination;
    }

    /**
     * @return string
     * 列表
     */
    public function actionList()
    {
        $params = \Yii::$app->request->getQueryParams();
        $this->layout = false;

        $params['page'] = empty($params['page']) ? self::PAGE : $params['page'];
        $params['pageSize'] = empty($params['pageSize']) ? self::PAGE_SIZE : $params['pageSize'];

        $list = Category::queryInfo($params);
        $count = Category::count($params);
        $pageNo = $params['page'] - 1;
        return $this->render('list', [
            'params' => $params,
            'list' => $list,
            'count' => $count,
            'pagination' => self::pagination($pageNo, $count),
        ]);
    }

    /**
     * 添加
     */
    public function actionAdd()
    {
        if (\Yii::$app->request->isGet) {
            $this->layout = false;
            return $this->render('add');
        } else {
            $params = \Yii::$app->request->post();
            $result = Category::add($params['name']);
            if ($result) {
                $this->jsonReturnSuccess(Constants::CODE_SUCCESS, $result, 'success');
            }
            $this->jsonReturnError(Constants::CODE_FAILED, 'fail');
        }
    }

    /**
     * 编辑
     */
    public function actionEdit()
    {
        if (\Yii::$app->request->isGet) {
            $params = \Yii::$app->request->getQueryParams();
            $this->layout = false;
            return $this->render('edit', [
                'params' => $params
            ]);
        } else {//编辑保存
            $params = \Yii::$app->request->post();
            $result = Category::edit($params['id'], $params['name']);
            if ($result) {
                $this->jsonReturnSuccess(Constants::CODE_SUCCESS, $result, 'success');
            }
            $this->jsonReturnError(Constants::CODE_FAILED, 'fail');
        }
    }

    /**
     * 删除
     */
    public function actionDel()
    {
        $params = \Yii::$app->request->getQueryParams();
        $result = Category::del($params['id']);
        if ($result) {
            $this->jsonReturnSuccess(Constants::CODE_SUCCESS, $result, 'success');
        }
        $this->jsonReturnError(Constants::CODE_FAILED, 'fail');
    }

}