<?php

namespace app\backend\controllers;

use app\common\models\ReleaseInfo;
use app\common\services\CommonService;

class IndexController extends BaseController
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function afterAction($action, $result)
    {
        $admin_name = \Yii::$app->session['admin_name'];
        $admin_id = \Yii::$app->session['admin_id'];
        if (empty($admin_name) || empty($admin_id)) {
            $this->redirect('/user/login');
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDesktop()
    {
        $this->layout = false;
        $username = \Yii::$app->session['admin_name'];

        $total = ReleaseInfo::total();//消息总数
        $top_total = ReleaseInfo::total(1);//置顶总数

        $created = strtotime(date('Y-m-d 00:00:00', strtotime('-29 days')));
        //统计最近30条的消息
        $list = ReleaseInfo::queryInfoCountLast30Days($created);
        $timeMap = CommonService::buildTimeMap($created, $_SERVER['REQUEST_TIME']);
        $dates = array_keys($timeMap);
        if (!empty($list)) {
            $itemList = array_column($list, 'count', 'logTime');
            $itemList = array_values(array_merge($timeMap, $itemList));
        } else {
            $itemList = array_values($timeMap);
        }
        return $this->render('desktop', [
            'total' => $total,
            'top_total' => $top_total,
            'dates' => json_encode($dates),
            'itemList' => json_encode($itemList),
            'username' => $username
        ]);
    }
}


