#!/usr/bin/env php
<?php

require(__DIR__ . '/common/config/init.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/console/config/main.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
