<?php

namespace app\common\models;

class Admin extends Base
{

    public static function tableName()
    {
        return 't_admin'; // TODO: Change the autogenerated stub
    }

    /**
     * 登录
     */
    public static function login($username, $password)
    {
        $model = static::find();
        $model->andWhere('isDelete=0');
        $model->andWhere('username="' . $username . '"');
        $model->andWhere('password="' . $password . '"');
        $model = $model->one();

        if (empty($model)) {
            return false;
        }
        return $model->id;
    }

    private static function bindParams($find, $params)
    {
        if (!empty($params['username'])) {
            $find->andWhere('username like "%' . $params['username'] . '%"');
        }
        $find->andWhere('isDelete=0');
        return $find;
    }

    /**
     * 列表
     */
    public static function queryList($params)
    {
        $offset = 0;
        if (!empty($params['page']) && !empty($params['pageSize'])) {
            $offset = ($params['page'] - 1) * $params['pageSize'];
        }

        $find = static::find();
        $find = static::bindParams($find, $params);

        $result = $find->select('id,username,nickname,head_pic,mobile,wx,email,status,created')
            ->offset($offset)
            ->orderBy('created desc')
            ->limit($params['pageSize'])
            ->asArray()
            ->all();
        return $result;
    }

    public static function count($params)
    {
        $find = static::find();
        $find = static::bindParams($find, $params);
        return $find->count();
    }

    /**
     * 删除
     */
    public static function del($id)
    {
        $model = static::find()->andWhere('id=' . $id)->one();
        if (!empty($model)) {
            $model->isDelete = 1;
            $model->updated = $_SERVER['REQUEST_TIME'];
            return $model->save();
        }
        return 0;
    }

    /**
     * 添加
     */
    public static function add($params)
    {
        $model = new self();
        $model->username = trim($params['username']);
        $model->nickname = trim($params['nickname']);
        $model->mobile = empty($params['mobile']) ? '' : trim($params['mobile']);
        $model->wx = empty($params['wx']) ? '' : trim($params['wx']);
        $model->password = trim($params['password']);//未加密
        $model->email = empty($params['email']) ? '' : trim($params['email']);
        $model->status = isset($params['status']) ? $params['status'] : 0;
        $model->isDelete = 0;
        $model->created = $_SERVER['REQUEST_TIME'];
        $model->updated = $_SERVER['REQUEST_TIME'];

        return $model->save();
    }

    /**
     * 编辑
     */
    public static function edit($params)
    {
        $model = static::find()->where('isDelete=0 and id=' . $params['id'])->one();
        if (!empty($model)) {
            if (!empty($params['username'])) {
                $model->username = trim($params['username']);
            }
            if (!empty($params['nickname'])) {
                $model->nickname = trim($params['nickname']);
            }
            if (!empty($params['mobile'])) {
                $model->mobile = trim($params['mobile']);
            }
            if (!empty($params['wx'])) {
                $model->wx = trim($params['wx']);
            }
            if (!empty($params['password'])) {
                $model->password = trim($params['password']);
            }
            if (!empty($params['email'])) {
                $model->email = trim($params['email']);
            }
            if (isset($params['status'])) {
                $model->status = trim($params['status']);
            }

            $model->updated = $_SERVER['REQUEST_TIME'];
            return $model->save();
        }
        return 0;
    }

    public static function queryById($id, $isObject = false)
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $find->andWhere('id=' . $id);
        $result = $find->asArray()->one();
        return $result;
    }
}