<?php

namespace app\common\models;

/**
 * Class Category
 * @package app\common\models
 * 分类
 */
class Category extends Base
{
    public static function tableName()
    {
        return 't_category'; // TODO: Change the autogenerated stub
    }


    /**
     * 绑定参数
     */
    private static function bindParams($find, $params)
    {
        if (!empty($params['name'])) {
            $find->andWhere('name like "%' . $params['name'] . '%"');
        }
        $find->andWhere('isDelete=0');
        return $find;
    }

    /**
     * 分类
     */
    public static function queryInfo($params)
    {
        $offset = 0;
        if (!empty($params['page']) && !empty($params['pageSize'])) {
            $offset = ($params['page'] - 1) * $params['pageSize'];
        }
        $find = static::find();
        $find = static::bindParams($find, $params);
        $result = $find->select('id,name,created')
            ->offset($offset)
            ->orderBy('created desc')
            ->limit($params['pageSize'])
            ->asArray()
            ->all();
        return $result;
    }

    /**
     * 分类
     */
    public static function count($params)
    {
        $find = static::find();
        $find = static::bindParams($find, $params);
        $count = $find->count();
        return $count;
    }

    /**
     * 获取所有的分类Id映射
     */
    public static function categoryMap()
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $result = $find->select('id,name')
            ->asArray()
            ->all();
        if (!empty($result)) {
            $list = [];
            foreach ($result as $key => $val) {
                $list[$val['id']] = $val['name'];
            }
            return $list;
        }
        return $result;
    }

    /**
     * 删除
     */
    public static function del($id)
    {
        $model = static::find()->where('id=' . $id)->one();
        if (!empty($model)) {
            $model->isDelete = 1;
            $model->updated = $_SERVER['REQUEST_TIME'];
            return $model->save();
        }
        return 0;
    }

    /**
     * 编辑
     */
    public static function edit($id, $name)
    {
        $model = static::find()->where('id=' . $id)->one();
        if (!empty($model)) {
            $model->name = trim($name);
            $model->updated = $_SERVER['REQUEST_TIME'];
            return $model->save();
        }
        return 0;
    }

    /**
     * 新增
     */
    public static function add($name)
    {
        $model = new self();
        $model->name = trim($name);
        $model->isDelete = 0;
        $model->created = $_SERVER['REQUEST_TIME'];
        $model->updated = $_SERVER['REQUEST_TIME'];
        return $model->save();
    }
}