<?php

namespace app\common\models;

use yii\db\ActiveRecord;

class FusilladeAttribute extends ActiveRecord
{
    public static function tableName()
    {
        return 't_fusillade_attribute'; // TODO: Change the autogenerated stub
    }

    public static function queryInfo($params)
    {
        $offset = 0;
        if (!empty($params['page']) && !empty($params['defaultPageSize'])) {
            $offset = ($params['page'] - 1) * $params['defaultPageSize'];
        }
        $find = static::find();
        $find = self::buildParams($find, $params);
        $result = $find->offset($offset)->select('id,amount,description')
            ->limit($params['defaultPageSize'])
            ->orderBy('amount desc')
            ->asArray()
            ->all();
        return $result;
    }

    /**
     * 统计记录数
     *
     * @param $params
     * @return mixed
     */
    public static function queryInfoNum($params)
    {
        $find = static::find();
        $find = self::buildParams($find, $params);
        return $find->count();
    }

    /**
     * 查询参数绑定
     *
     * @param $find
     * @param $params
     * @return mixed
     */
    public static function buildParams($find, $params)
    {
        return $find;
    }
}