<?php
namespace app\common\models;

use yii\db\ActiveRecord;
use Yii;

class GiftFire extends ActiveRecord{

    public static function tableName()
    {
        return 't_gift_fire'; // TODO: Change the autogenerated stub
    }

    public static function executeBySqlCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->execute();
    }

    //查询到连发数据
    public static function selectGiftFire(){
        $sql = "SELECT `id`,`number`,`meaning` FROM ".static ::tableName()." LIMIT 6";
        $result = Yii::$app->db->createCommand($sql)->queryAll();
        return $result;
    }
    //插入数据连发
    public static function batchInsertGiftFire($data){

        if (!empty($data) && isset($data)) {
            foreach ($data as $key => $val){
                $model = static::find()->andWhere(['id' => $val['id']])->one();
                if(!empty($model)){
                    $model->number  = $val['number'];
                    $model->meaning = $val['meaning'];
                }
                else{
                    $model = new self();
                    $model->number  = $val['number'];
                    $model->meaning = $val['meaning'];
                    $model->created = $_SERVER['REQUEST_TIME'];
//                    $model->updated = $_SERVER['REQUEST_TIME'];
//                    $model->save();
                }
                $model->updated = $_SERVER['REQUEST_TIME'];
                $model->save();
            }
            return ['code'=>0];
        }
        else {
            return ['code'=>-1];
        }
    }

}