<?php

namespace app\common\models;

use yii\db\ActiveRecord;

class Order extends ActiveRecord
{
    public static function tableName()
    {
        return 't_order'; // TODO: Change the autogenerated stub
    }

    //购买礼物
    public static function create($giftId, $userId, $userIdReceive, $price, $num)
    {
        $model = new self();
        $model->giftId = $giftId;
        $model->price = $price;
        $model->priceReal = $price;
        $model->num = $num;
        $model->userIdReceive = $userIdReceive;
        $model->created = time();
        $model->updated = time();
        $model->save();
        return $model;
    }
}