<?php

namespace app\common\models;

class Profession extends Base
{
    public static function tableName()
    {
        return 't_profession'; // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @param string $field
     * @param string $orderBy
     * @return mixed
     */
    public static function queryInfo($params, $field = '', $orderBy = 'created desc')
    {
        $offset = 0;
        if (!empty($params['page']) && !empty($params['defaultPageSize'])) {
            $offset = ($params['page'] - 1) * $params['defaultPageSize'];
        }
        $find = static::find();
        $find = self::buildParams($find, $params);
        return $find->asArray()
            ->select(!empty($field) ? $field : '*')
            ->offset($offset)
            ->orderBy($orderBy)
            ->limit($params['defaultPageSize'])
            ->all();
    }

    /**
     * @param $find
     * @param $params
     * @return mixed
     */
    protected static function buildParams($find, $params)
    {
        if (isset($params['id'])) {
            $find->andWhere('id=' . $params['id']);
        }
        return $find;
    }
}