<?php

namespace app\common\models;

use yii\db\ActiveRecord;
use Yii;

class ReportOptions extends ActiveRecord
{
    public static function tableName()
    {
        return 't_report_options'; // TODO: Change the autogenerated stub
    }

    /**
     * 通过ID查询
     *
     * @param $id
     * @param bool $isObject
     * @return mixed
     */
    public static function queryById($id, $isObject = false)
    {
        $find = static::find();
        $find = self::buildParams($find, [['id' => $id]]);
        if ($isObject) {
            return $find->one();
        } else {
            return $find->asArray()->one();
        }
    }
    /**
     * @param $params
     * @param null $fields
     * @return mixed
     */
    public static function queryInfo($params, $fields = null)
    {
        $offset = 0;
        if (!empty($params['page']) && !empty($params['defaultPageSize'])) {
            $offset = ($params['page'] - 1) * $params['defaultPageSize'];
        }
        $find = static::find();
        $find = self::buildParams($find, $params);
        if (!empty($fields)) {
            $find->select($fields);
        }
        return $find->asArray()->offset($offset)
            ->orderBy('created desc')
            ->limit($params['defaultPageSize'])->all();
    }

    /**
     * @param $params
     * @return mixed
     */
    public static function queryInfoNum($params)
    {
        $find = static::find();
        $find = self::buildParams($find, $params);
        return $find->count();
    }

    /**
     * @param $find
     * @param $params
     * @return mixed
     */
    private static function buildParams($find, $params)
    {
        if (isset($params['id'])) {
            $find->andWhere('id=' . $params['id']);
        }
        return $find;
    }

    //查询到连发数据
    public static function selectReportType(){
        $sql = "SELECT `id`,`content` FROM ".static ::tableName()." WHERE isDelete =0  LIMIT 5";
        $result = Yii::$app->db->createCommand($sql)->queryAll();
        return $result;
    }

    //保存举报类型
    public static function saveReportType($data){
        if (!empty($data) && isset($data)) {
            foreach ($data as $key => $val){
                $model = static::find()->andWhere(['id' => $val['id']])->one();
                if(!empty($model)){
                    $model->content  = $val['content'];
                }
                else{
                    $model = new self();
                    $model->content  = $val['content'];
                    $model->created = $_SERVER['REQUEST_TIME'];
                }
                $model->updated = $_SERVER['REQUEST_TIME'];
                $model->save();
            }
            return ['code'=>0];
        }
        else {
            return ['code'=>-1];
        }
    }

}