<?php
namespace app\common\models;

use yii\db\ActiveRecord;
use Yii;

class ShareSlogan extends ActiveRecord{

    public static function tableName()
    {
        return 't_share_slogan'; // TODO: Change the autogenerated stub
    }

    public static function queryOneBySQLCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->queryOne();
    }

    public static function queryBySQLCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->queryAll();
    }

    public static function executeBySqlCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->execute();
    }
    //查询分享标语
    public static function queryShareSlogan(){

        $sql = "SELECT id,title,content FROM ".static ::tableName()." LIMIT 1";

//        $model = static ::find()->where(['id' => $id])->one();
        return static ::queryOneBySQLCondition($sql);

    }


}