<?php
namespace app\common\models;

use yii\db\ActiveRecord;
use Yii;

class ShareSlogan extends ActiveRecord{

    public static function tableName()
    {
        return 't_share_slogan'; // TODO: Change the autogenerated stub
    }

    public static function queryOneBySQLCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->queryOne();
    }

    public static function queryBySQLCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->queryAll();
    }

    public static function executeBySqlCondition($sql = '')
    {
        $connection = Yii::$app->db;
        $command = $connection->createCommand($sql);
        return $command->execute();
    }
    //查询分享标语
    public static function queryShareSlogan(){

        $sql = "SELECT id,title,content FROM ".static ::tableName()." LIMIT 1";

//        $model = static ::find()->where(['id' => $id])->one();
        return static ::queryOneBySQLCondition($sql);

    }

    //如果有数据则保存，没数据就插入
    public static function udpateShareSlogan($data){

        if (!empty($data) && isset($data)) {
            $model = static::find()->andWhere(['id' => $data['id']])->one();
            if(!empty($model)){
                $model->title  = $data['title'];
                $model->content = $data['content'];
            }
            else{
                $model = new self();
                $model->title  = $data['title'];
                $model->content = $data['content'];
                $model->created = $_SERVER['REQUEST_TIME'];
            }
            $model->updated = $_SERVER['REQUEST_TIME'];
            $model->save();
            return ['code'=>0];
        }
        else {
            return ['code'=>-1];
        }
    }


}