<?php

namespace app\common\models;

/**
 * Class StickyCode
 * @package app\common\models
 * 置顶码
 */
class StickyCode extends Base
{
    public static function tableName()
    {
        return 't_sticky_code'; // TODO: Change the autogenerated stub
    }

    /**
     * 根据置顶码设置权重
     */
    public static function getWeightByCode($code)
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $find->andWhere('code="' . $code . '"');
        $result = $find->select('weight,valid_time,created')
            ->asArray()
            ->one();
        if (!empty($result)) {
            return $result;
        }
        return [];
    }

    /**
     * 生成置顶码
     */
    public static function createCode($code, $weight = 0, $valid_time = 0)
    {
        $model = new self();
        $model->code = $code;
        $model->weight = $weight;
        $model->valid_time = time() + $valid_time;
        $model->isDelete = 0;
        $model->created = $_SERVER['REQUEST_TIME'];
        $model->updated = $_SERVER['REQUEST_TIME'];

        return $model->save();
    }

    /**
     * 查询需要更新状态的置顶码
     */
    public static function queryCodeInfo()
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $result = $find->select('id,valid_time')
            ->asArray()
            ->all();
        return $result;
    }

    /**
     * 更新置顶码状态
     * 异步更新
     */
    public static function updateCodeStatus($ids)
    {
        $sql = "UPDATE " . static::tableName() . " set isDelete=1 WHERE id in (" . $ids . ")";
        return static::updateBySqlCondition($sql);
    }

    /**
     * 让置顶码失效
     */
    public static function delCode($code)
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $model = $find->andWhere('code="' . $code . '"')->one();

        if (!empty($model)) {
            $model->isDelete = 1;
            $model->updated = $_SERVER['REQUEST_TIME'];
            return $model->save();
        }
        return 0;
    }
}