<?php

namespace app\common\models;

class UserInfo extends Base
{
    public static function tableName()
    {
        return 't_user'; // TODO: Change the autogenerated stub
    }

    /**
     * 验证手机号码
     */
    public static function verifyPhone($phone)
    {
        $find = static::find();
        $find->andWhere('isDelete=0');
        $find->andWhere('phone="' . $phone . '"');
        $result = $find->one();
        if (!empty($result)) {
            return true;
        }
        return false;
    }
}