<?php
namespace app\common\models;

use yii\db\ActiveRecord;
use Yii;

class UserFeedback extends ActiveRecord{

    public static function tableName()
    {
        return 't_user_feedback'; // TODO: Change the autogenerated stub
    }

    //插入反馈内容
    public static function insertUserFeedback($params){

        $model = new self();
        $model->userId = intval($params['id']);
        $model->content = $params['content'];
        $model->created = $_SERVER['REQUEST_TIME'];
        $model->updated = $_SERVER['REQUEST_TIME'];
        $model->save();
        return $model->id;
    }
}